/**
 * Packs `data/solar-terms.json` into `data/solar-terms.packed.ts`, the form
 * the engine ships (M19.8-08): the first instant in epoch milliseconds, then
 * each jié as the millisecond gap from the one before. Names and longitudes
 * repeat every 12 entries, so the file keeps that 12-entry cycle once — copied
 * from the JSON and checked against every entry, never typed by hand.
 *
 * Runs after generate-solar-terms.ts (`pnpm generate:solar-terms` does both).
 * The JSON stays the audited source; test/solar-terms-packed.test.ts proves
 * the packed file decodes back to it exactly.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Entry {
  name: string;
  longitude: number;
  iso: string;
}

const CYCLE_LENGTH = 12;
const NUMBERS_PER_LINE = 8;

const dataDir = join(dirname(fileURLToPath(import.meta.url)), "..", "data");
const entries = JSON.parse(readFileSync(join(dataDir, "solar-terms.json"), "utf8")) as Entry[];

const cycle = entries.slice(0, CYCLE_LENGTH).map(({ name, longitude }) => ({ name, longitude }));
entries.forEach((entry, index) => {
  const expected = cycle[index % CYCLE_LENGTH]!;
  if (entry.name !== expected.name || entry.longitude !== expected.longitude) {
    throw new Error(`Entry ${index} (${entry.iso}) breaks the 12-jié cycle`);
  }
});

const epochs = entries.map((entry) => Date.parse(entry.iso));
const deltas = epochs.slice(1).map((epoch, index) => epoch - epochs[index]!);
if (deltas.some((delta) => delta <= 0)) {
  throw new Error("Solar terms are not strictly increasing");
}

const deltaLines: string[] = [];
for (let start = 0; start < deltas.length; start += NUMBERS_PER_LINE) {
  deltaLines.push(`  ${deltas.slice(start, start + NUMBERS_PER_LINE).join(", ")},`);
}

const source = `/**
 * GENERATED by scripts/pack-solar-terms.ts from data/solar-terms.json — do not
 * edit. The JSON (astronomy-engine, 1900–2100, scripts/generate-solar-terms.ts)
 * is the audited source; this is the same ${entries.length} jié packed for the
 * browser bundle. test/solar-terms-packed.test.ts proves they match exactly.
 */

/** Name and ecliptic longitude of each jié, repeating every ${CYCLE_LENGTH} entries from the first. */
export const JIE_CYCLE: readonly { name: string; longitude: number }[] = ${JSON.stringify(cycle)};

/** Instant of the first jié, epoch milliseconds (${entries[0]!.iso}). */
export const FIRST_JIE_EPOCH_MS = ${epochs[0]};

/** Milliseconds from each jié to the next, in order. */
export const JIE_GAPS_MS: readonly number[] = [
${deltaLines.join("\n")}
];
`;

writeFileSync(join(dataDir, "solar-terms.packed.ts"), source);
console.log(`Packed ${entries.length} solar terms into data/solar-terms.packed.ts`);
